### PR TITLE
Add a resource from 'Grow Beyond with Google'

### PR DESCRIPTION
**Pull request by wgx731**
Just another resource I found useful to share with other student who didn't participate in the 'Grow beyond with Google' program. :thumbsup:

### CODE REVIEW

**Comment by ymichael** [comment]
create an `_assets` folder and serve it from this repo itself?

**Comment by wgx731** [comment]
@ymichael and @ejamesc, the problem I am facing is that the source file I have is a PDF file if I upload to Google Drive the links are not able to access. That's why I put it in Dropbox. But now I have add the source file in `_assets` folder, not sure the link works or not as I can't test it locally. Wish it helps for others.

**Comment by ymichael** [comment]
Can you change the link to be relative instead of absolute? See how the css files are linked in... Thanks!

**Comment by wgx731** [comment]
@ymichael, Sorry I didn't notice https://github.com/blog/1395-relative-links-in-markup-files. Changed to relative link now. Thanks for letting me know it. :+1:

**Comment by ymichael** [comment]
Awesome. Thanks.

**Pull request merged**
